name: Production

on:
  push:
    branches:
    - master
    - uat

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        MASTER_ENV: ${{ secrets.MASTER_ENV }}
        UAT_ENV: ${{ secrets.UAT_ENV }}
      run: |
        npm install
        ./customize_configs.sh
        mkdir -p stitch/hosting/files
        npm run build-prod
        echo "<!-- $(date) -->" >> stitch/hosting/files/index.html
    - name: Deploy
      env:
        MASTER_ENV: ${{ secrets.MASTER_ENV }}
        UAT_ENV: ${{ secrets.UAT_ENV }}
        STITCH_API_KEY: ${{ secrets.STITCH_API_KEY }}
        STITCH_USER: ${{ secrets.STITCH_USER }}
      run: |
        ./deploy_app.sh
