name: Production

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        STITCH_APP_ID: ${{ secrets.PROD_STITCH_APP_ID }}
      run: |
        npm install
        sed -i "s/GITHUB_STITCH_APP_ID/$STITCH_APP_ID/" src/js/app.js
        mkdir -p stitch/hosting/files
        npm run build-prod
        echo "<!-- $(date) -->" >> stitch/hosting/files/index.html
    - name: Deploy to Production
      env:
        STITCH_APP_ID: ${{ secrets.PROD_STITCH_APP_ID }}
        STITCH_API_KEY: ${{ secrets.STITCH_API_KEY }}
        STITCH_USER: ${{ secrets.STITCH_USER }}
      run: |
        stitch-cli login --api-key "$STITCH_API_KEY" --username "$STITCH_USER"
        stitch-cli import --strategy=merge --include-hosting --reset-cdn-cache --yes
